### ISSUE TITLE
Will you ever update this

### ISSUE THREAD

**Issue by GhostingGodzilla** [agent86ix/openmaul#2]

**Comment by agent86ix** [comment]
Nope.  I put this together as part of a project for a clan I was a part of 10+ years ago.  

When I left the clan, I open-sourced the parts I worked on so the clan could continue development.

I don't play any games that this would work for anymore (and honestly haven't since I left that clan), and there's a whole backend that someone else wrote that I don't have access to.  

So this is here for that clan's benefit and basically nobody else.

**Comment by GhostingGodzilla** [comment]
okay that's what I figured I was just curious. you guys did a very nice job doing it for the eGO
